electPowerConsData = read.csv("household_power_consumption.txt", sep = ";", stringsAsFactors = FALSE, na.strings = "?")
electPowerConsData = electPowerConsData[electPowerConsData$Date == "1/2/2007" | electPowerConsData$Date == "2/2/2007",]
datetime = strptime(paste(electPowerConsData$Date, electPowerConsData$Time, sep = " "), format = "%d/%m/%Y %H:%M:%S")
png("plot3.png")
plot(datetime, electPowerConsData$Sub_metering_1, type = "n", xlab = "", ylab = "Energy sub metering")
points(datetime, electPowerConsData$Sub_metering_1, type = "l", col = "black")
points(datetime, electPowerConsData$Sub_metering_2, type = "l", col = "red")
points(datetime, electPowerConsData$Sub_metering_3, type = "l", col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()